### ISSUE TITLE
Broken and Unusable

### ISSUE THREAD

**Issue by ghost** [graphitemaster/glsl-parser#17]
Just to save time from any future users looking to make a GLSL tool from this repo, this library is:

 - non-conforming to GLSL (see #10 as just one example, does not handle escaped newlines as another example)
 - riddled with memory access errors (more than what's mentioned in #13)
 - no longer maintained (see commit history)
 - generally incomplete (no parsing of directives)

Don't let the GitHub star count fool you like they did me! As of writing this, there doesn't seem to be a solid C++ library for parsing GLSL code aside from the one in [glslang](https://github.com/KhronosGroup/glslang/blob/master/glslang/Include/glslang_c_interface.h), which is wrapped in a C API.

I mean no offense to the author or co-authors, just trying to save someone time from trying to use this code.

**Comment by graphitemaster** [comment]
If you find legitimate bugs in this project it would do you and others a lot better to report them and give me time to both verify and fix the issues, rather than opening bugs, immediately closing them and then ranting in another issue warning people not to use the code.

I don't understand where your sense of entitlement comes from, it's an open source, low-priority (for me) code base that I could've left closed and not shared with anyone, and your abrasiveness is why a lot of people just don't want to do OSS. I get it, you probably cloned it and started using it and began running into problems and now you're frustrated, we've all been there.

Had you reported the issues and given me time (I'm actually quite busy as of current) I could've fixed them. Some of them look fairly trivial (as you've concluded) and you could've even given back to me and the community by fixing them and opening PRs as well.

Try to be a little more respectful of what is effectively given to you for free. I'll look at the issues you've commented on and complained about when I have some time. You're free to use something else if you're impatient.

**Comment by ghost** [comment]
It's not a sense of entitlement and I don't mean to be disrespectful. I certaintly don't want to keep people from doing OSS. Reading my first post, I can see why it seems abrasive, my apologies.

The README can easily lead people to believe that this is a finished project. Perhaps you can add a note in there so that people know this library is still a WIP? I've seen other libraries do that, and it helps other people have better expectations when trying to use the code. Some of the issues with this project are non-trivial (none of the directives are implemented, for example).

**Comment by graphitemaster** [comment]
I've fixed several of the issues outlined in existing issues and closed the appropriate ones. The README has been updated to reflect some known limitations. If you have any other concerns open up some issues or PRs, thanks.
